targets:
  $default:
    builders:
      json_serializable:
        options:
          any_map: false
          checked: true
          constructor: ""
          create_factory: true
          disallow_unrecognized_keys: true
          explicit_to_json: true
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true